### ISSUE TITLE
Windows: Midi ports spawn don't work

### ISSUE THREAD

**Issue by piscue** [piscue/network-midi-hub#14]
```
C:\Users\User\git\network-midi-hub\dist> .\client.exe
Host to connect [127.0.0.1]: 
Traceback (most recent call last):
  File "client.py", line 174, in <module>
  File "client.py", line 133, in main
  File "mido\backends\backend.py", line 91, in open_input
  File "mido\ports.py", line 161, in __init__
  File "mido\ports.py", line 86, in __init__
  File "mido\backends\rtmidi.py", line 124, in _open
  File "mido\backends\rtmidi.py", line 80, in _open_port
  File "src\_rtmidi.pyx", line 642, in rtmidi._rtmidi.MidiBase.open_virtual_port
NotImplementedError: Virtual ports are not supported by the Windows MultiMedia API.
[12736] Failed to execute script client
```

**Comment by piscue** [comment]
The crash in the original report came from calling `open_virtual_port` on Windows, which the Windows MultiMedia API does not support. This was fixed in commit 55d6c9d — the client now has a dedicated Windows branch that opens named loopMIDI ports and falls back to interactive port selection on `OSError`, without ever calling `open_virtual_port`. No code change needed. Closing.
